export interface Exercise {
  id: string;
  title: string;
  difficulty: "warm-up" | "core" | "stretch";
  goal: string;
  hint: string;
  outcome: string;
  proTip: string | null;
}

export interface Level {
  id: number;
  title: string;
  theme: string;
  exercises: Exercise[];
}

export const levels: Level[] = [
  {
    id: 1,
    title: "Explore and Orient",
    theme: "Learn to ask your AI tool questions about code",
    exercises: [
      {
        id: "1-1",
        title: "What does this project do?",
        difficulty: "warm-up",
        goal: "Ask your AI tool to explain the project structure and what each file does.",
        hint: "Can you explain what this project does and walk me through each file?",
        outcome: "You understand that index.html is the page, main.ts has the logic, style.css has the styling, and sites.json has the data.",
        proTip: null,
      },
      {
        id: "1-2",
        title: "Explain a function",
        difficulty: "core",
        goal: "Ask AI to explain the calculateStats function in main.ts in plain English.",
        hint: "Explain what the calculateStats function in main.ts does, step by step, in non-technical language.",
        outcome: "AI breaks down that it counts total sites, counts active sites, sums up revenue, and averages CSAT scores.",
        proTip: null,
      },
      {
        id: "1-3",
        title: "Where does the data come from?",
        difficulty: "core",
        goal: "Ask AI to trace where the site data originates and how it flows to the table.",
        hint: "Trace the data flow -- where does the site data come from and how does it end up in the table?",
        outcome: "You understand the path: sites.json is imported in main.ts, filtered by applyFilters(), then rendered as table rows by renderTable().",
        proTip: null,
      },
      {
        id: "1-4",
        title: "What would happen if...?",
        difficulty: "stretch",
        goal: "Ask AI what would happen if you deleted the applyFilters() call near the bottom of main.ts.",
        hint: "What would happen if I removed the applyFilters() call near the bottom of main.ts?",
        outcome: "AI explains the page would load with an empty table and empty summary cards because nothing triggers the initial render.",
        proTip: null,
      },
      {
        id: "1-5",
        title: "What events fire?",
        difficulty: "stretch",
        goal: "Ask AI what event fires when the product filter dropdown is changed. Trace from the HTML element to the handler.",
        hint: "What event fires when the product filter dropdown is changed? Trace from the HTML element to the event listener.",
        outcome: "You understand that the 'change' event on #filter-product triggers the applyFilters function, which re-renders everything.",
        proTip: "In real production repos, you can ask AI to find event tracking instrumentation the same way -- \"What analytics event fires when a user clicks [button]?\"",
      },
      {
        id: "1-6",
        title: "Vague vs. structured prompt",
        difficulty: "stretch",
        goal: "See how prompt quality changes AI output by trying two versions of the same question.",
        hint: "First ask: \"Tell me about the data.\" Then ask: \"Analyze sites.json and give me a summary table showing: count of sites per product type, average CSAT per product type, and total monthly revenue per product type. Format as a markdown table.\" Compare the two responses.",
        outcome: "The vague prompt gives a generic overview. The structured prompt gives you an actionable table you could paste into a Slack message or a slide.",
        proTip: "The pattern is: specify the data source, the exact metrics you want, the grouping, and the output format. This works the same way when you ask AI to analyze a CSV, a database query result, or a QuickSight dataset.",
      },
    ],
  },
  {
    id: 2,
    title: "First Changes",
    theme: "Make your first visible modifications",
    exercises: [
      {
        id: "2-1",
        title: "Change the page title",
        difficulty: "warm-up",
        goal: "Update the header text from \"Site Dashboard\" to something of your own.",
        hint: "Change the h1 heading in index.html from 'Site Dashboard' to 'My Product Dashboard'.",
        outcome: "The header in your browser shows your new title.",
        proTip: null,
      },
      {
        id: "2-2",
        title: "Change the header color",
        difficulty: "warm-up",
        goal: "Swap the dark header background to a color you like.",
        hint: "Change the header background color in style.css from black (#111) to dark blue.",
        outcome: "The header bar in your browser is now the color you chose.",
        proTip: null,
      },
      {
        id: "2-3",
        title: "Edit a site name",
        difficulty: "core",
        goal: "Change \"Bella's Bakery\" to a business name you make up in sites.json.",
        hint: "In data/sites.json, change the name of the first site from 'Bella's Bakery' to 'Nealey's Taco Shop'.",
        outcome: "The first row in the table shows your new business name.",
        proTip: null,
      },
      {
        id: "2-4",
        title: "Add yourself",
        difficulty: "stretch",
        goal: "Add a 16th site to sites.json with your own made-up business.",
        hint: "Add a new site to data/sites.json with id 16, called [your business name], with WordPress as the product, active status, and a CSAT of 6.0.",
        outcome: "The table now shows 16 rows and the Total Sites card says 16.",
        proTip: null,
      },
    ],
  },
  {
    id: 3,
    title: "Read and Understand Data",
    theme: "Use AI to answer PM-relevant questions from the data",
    exercises: [
      {
        id: "3-1",
        title: "Which product has the most sites?",
        difficulty: "warm-up",
        goal: "Ask AI to analyze sites.json and tell you which product type has the most sites.",
        hint: "Look at data/sites.json and tell me which product type (WordPress, Managed WordPress, Websites + Marketing) has the most sites.",
        outcome: "AI tells you WordPress has 6 sites, Managed WordPress has 4, Websites + Marketing has 5.",
        proTip: null,
      },
      {
        id: "3-2",
        title: "Who has the worst CSAT?",
        difficulty: "core",
        goal: "Ask AI which site has the lowest CSAT and why that might matter from a PM perspective.",
        hint: "Which site in sites.json has the lowest CSAT score? What might that tell a product manager?",
        outcome: "AI identifies Paws & Play Pet Care (3.2) and may note it's also inactive -- low satisfaction may have led to churn.",
        proTip: null,
      },
      {
        id: "3-3",
        title: "Revenue breakdown",
        difficulty: "core",
        goal: "Ask AI to calculate total monthly revenue grouped by product type.",
        hint: "Calculate the total monthly revenue for each product type in sites.json.",
        outcome: "AI gives you revenue totals per product (WordPress, Managed WordPress, Websites + Marketing).",
        proTip: null,
      },
      {
        id: "3-4",
        title: "Find the AI Builder users",
        difficulty: "stretch",
        goal: "Ask AI which sites use the AI Builder plugin and what patterns you see.",
        hint: "Which sites in sites.json have 'AI Builder' in their plugins list? What do they have in common?",
        outcome: "AI identifies the AI Builder users and may note they tend to have higher CSAT scores and revenue.",
        proTip: "This is the kind of question PMs can ask AI about real product data -- finding patterns without writing SQL.",
      },
    ],
  },
  {
    id: 4,
    title: "Add Features",
    theme: "Extend the dashboard with new functionality",
    exercises: [
      {
        id: "4-1",
        title: "Add a Page Views column",
        difficulty: "warm-up",
        goal: "The data has pageViews but it's not displayed -- add it to the table.",
        hint: "Add a 'Page Views' column to the table in index.html and main.ts. The data already exists in sites.json as pageViews.",
        outcome: "A new Page Views column appears in the table with formatted numbers.",
        proTip: null,
      },
      {
        id: "4-2",
        title: "Add a Region column",
        difficulty: "core",
        goal: "Same idea with the region field from sites.json.",
        hint: "Add a Region column to the sites table, pulling from the region field in the data.",
        outcome: "A Region column appears showing US-West, US-East, US-Central, EU.",
        proTip: null,
      },
      {
        id: "4-3",
        title: "Conditional row highlighting",
        difficulty: "core",
        goal: "Make rows with CSAT below 4.0 stand out visually.",
        hint: "Highlight table rows in light red where the CSAT score is below 4.0.",
        outcome: "Paws & Play (3.2) and Green Valley Farm (3.8) rows are highlighted.",
        proTip: null,
      },
      {
        id: "4-4",
        title: "New summary card",
        difficulty: "stretch",
        goal: "Add a \"Total Page Views\" card to the summary section at the top.",
        hint: "Add a new summary card showing Total Page Views, summing the pageViews field from all filtered sites.",
        outcome: "A fifth card appears in the summary row showing total page views.",
        proTip: "Notice how the card updates when you filter -- the same filtering logic applies automatically.",
      },
    ],
  },
  {
    id: 5,
    title: "Bug Hunt",
    theme: "Find and fix a real bug hidden in the code",
    exercises: [
      {
        id: "5-1",
        title: "Spot the discrepancy",
        difficulty: "warm-up",
        goal: "Manually add up the monthly revenue for all 15 sites. Does the dashboard total match?",
        hint: "Open sites.json and add up all the monthlyRevenue values. Compare to what the dashboard shows.",
        outcome: "The dashboard shows a lower number than your manual calculation -- something is wrong.",
        proTip: null,
      },
      {
        id: "5-2",
        title: "Ask AI to find the bug",
        difficulty: "core",
        goal: "Tell AI the revenue total seems wrong and see if it can locate the issue.",
        hint: "The Monthly Revenue total on the dashboard doesn't match what I calculated manually from sites.json. Can you find the bug?",
        outcome: "AI identifies the off-by-one error in the for loop in calculateStats (i < filteredSites.length - 1 should be i < filteredSites.length).",
        proTip: null,
      },
      {
        id: "5-3",
        title: "Fix it",
        difficulty: "core",
        goal: "Use AI to fix the bug and verify the total is now correct.",
        hint: "Fix the revenue calculation bug you found and verify the total is now correct.",
        outcome: "The Monthly Revenue card now shows the correct total including the last site's revenue.",
        proTip: null,
      },
      {
        id: "5-4",
        title: "Understand git blame",
        difficulty: "stretch",
        goal: "Ask AI to show you which commit introduced the bug.",
        hint: "Use git log or git blame to show me which commit introduced the bug in the revenue calculation.",
        outcome: "AI shows you the commit \"Add dashboard logic with filtering and summary stats\" introduced the off-by-one error.",
        proTip: "In real projects, git blame helps PMs understand when and why a change was made -- useful for incident timelines.",
      },
    ],
  },
  {
    id: 6,
    title: "Data Analysis",
    theme: "Turn raw data into actionable insights",
    exercises: [
      {
        id: "6-1",
        title: "Sort the table",
        difficulty: "core",
        goal: "Make table column headers clickable to sort ascending/descending.",
        hint: "Make the table headers clickable so clicking a column sorts the table by that column. Clicking again should reverse the sort order.",
        outcome: "Clicking \"CSAT\" sorts sites by CSAT score, clicking again reverses the order.",
        proTip: null,
      },
      {
        id: "6-2",
        title: "Revenue by product",
        difficulty: "core",
        goal: "Add a visible breakdown showing total revenue grouped by product type.",
        hint: "Add a section below the summary cards showing total monthly revenue broken down by product type.",
        outcome: "A new section appears showing revenue totals per product type.",
        proTip: null,
      },
      {
        id: "6-3",
        title: "CSAT distribution",
        difficulty: "core",
        goal: "Show how many sites fall into each CSAT bucket (good/ok/bad).",
        hint: "Add a visual showing how many sites have good CSAT (5.5+), ok CSAT (4.0-5.4), and bad CSAT (below 4.0).",
        outcome: "A breakdown showing the count per bucket (e.g., 6 good, 4 ok, 2 bad).",
        proTip: null,
      },
      {
        id: "6-4",
        title: "Top performers",
        difficulty: "stretch",
        goal: "Highlight or badge the top 3 sites by page views.",
        hint: "Add a visual indicator (like a star or badge) to the top 3 sites by page views in the table.",
        outcome: "The 3 highest-traffic sites have a visible badge or highlight.",
        proTip: null,
      },
    ],
  },
  {
    id: 7,
    title: "Visualization",
    theme: "Add charts and visual data stories",
    exercises: [
      {
        id: "7-1",
        title: "Bar chart",
        difficulty: "core",
        goal: "Add a bar chart showing CSAT scores by site using pure HTML/CSS.",
        hint: "Add a horizontal bar chart below the table showing CSAT scores for each site. Use colored div elements with widths based on the CSAT score -- no charting library needed.",
        outcome: "A bar chart appears with each site's CSAT score visualized as colored bars.",
        proTip: null,
      },
      {
        id: "7-2",
        title: "Pie chart",
        difficulty: "core",
        goal: "Add a pie chart showing the product type distribution using CSS.",
        hint: "Add a pie chart showing what percentage of sites use each product type (WordPress, Managed WordPress, Websites + Marketing). Use a CSS conic-gradient approach -- no library needed.",
        outcome: "A pie chart appears with 3 segments showing the product mix.",
        proTip: null,
      },
      {
        id: "7-3",
        title: "Make it interactive",
        difficulty: "stretch",
        goal: "Add hover tooltips or click interactions to a chart.",
        hint: "Make the bar chart interactive -- show the exact CSAT score and site name when you hover over a bar. Use CSS :hover and a tooltip element.",
        outcome: "Hovering over chart elements reveals details.",
        proTip: "For production dashboards you'd use Chart.js or D3 -- but pure CSS charts are great for quick prototypes and keep this project dependency-free.",
      },
    ],
  },
  {
    id: 8,
    title: "Build a New View",
    theme: "Create something that doesn't exist yet",
    exercises: [
      {
        id: "8-1",
        title: "Site detail panel",
        difficulty: "core",
        goal: "When you click a site name in the table, show a detail panel with all of that site's information.",
        hint: "When I click a site name in the table, show a slide-out panel on the right with all details for that site including plugins, page views, and region.",
        outcome: "Clicking a site name opens a detail view showing fields not in the table.",
        proTip: null,
      },
      {
        id: "8-2",
        title: "Comparison mode",
        difficulty: "stretch",
        goal: "Let users select two sites and see a side-by-side comparison.",
        hint: "Add checkboxes to each row and a 'Compare' button that shows a side-by-side comparison of the selected sites.",
        outcome: "Selecting two sites and clicking Compare shows their stats side-by-side.",
        proTip: null,
      },
      {
        id: "8-3",
        title: "Executive summary view",
        difficulty: "stretch",
        goal: "Add a toggleable executive summary view within the existing page.",
        hint: "Add a 'Summary View' toggle button in the header. When clicked, hide the table and show an executive overview section with total sites, total revenue, average CSAT, and top/bottom performers. Clicking 'Table View' switches back.",
        outcome: "A toggle switches between the detailed table and a high-level executive view, all within the same page.",
        proTip: null,
      },
      {
        id: "8-4",
        title: "Build from a screenshot",
        difficulty: "stretch",
        goal: "Take a screenshot of any UI you like (a competitor's dashboard, a Figma mock, a sketch on paper) and use it as an AI input to generate code.",
        hint: "Take a screenshot and paste it into the AI chat. Then say: \"Build me a component that looks like this screenshot. Use the same layout and visual style but populate it with data from sites.json.\"",
        outcome: "AI generates a new section or component that visually matches your reference image, wired to real data.",
        proTip: "This is one of the highest-leverage PM workflows -- go from a whiteboard sketch or Figma mock to a working prototype in minutes. Some PMs use this to estimate LOE by asking \"how complex would this be to build?\" after the AI generates the code.",
      },
    ],
  },
  {
    id: 9,
    title: "Prototype Your Own Idea",
    theme: "Apply vibe coding to your actual PM work",
    exercises: [
      {
        id: "9-1",
        title: "Identify a real problem",
        difficulty: "warm-up",
        goal: "Think about a task from your PM workflow that you currently do manually or ask engineering for help with.",
        hint: "No AI prompt needed -- just reflect. Examples: a prioritization scorecard, a competitive comparison table, a release checklist, a customer feedback tracker.",
        outcome: "You have a concrete idea for something you want to build. You can describe it in one sentence.",
        proTip: null,
      },
      {
        id: "9-2",
        title: "Write a mini-spec first",
        difficulty: "core",
        goal: "Before prompting AI, write a short spec for your idea -- 3-5 bullet points covering what it does, what data it needs, and what the output looks like.",
        hint: "Write something like: \"Tool: Priority Scorecard. Purpose: Rank feature requests by impact and effort. Data: a list of features with name, impact score (1-5), effort score (1-5), and requestor. Output: a table sorted by impact/effort ratio with color-coded priority bands.\"",
        outcome: "You have a structured spec you can hand to AI instead of a vague description.",
        proTip: "PMs who write a spec before prompting get dramatically better first-pass output. It also becomes the acceptance criteria -- you can tell AI \"this doesn't match the spec, the table should be sorted by ratio\" instead of vague feedback. This is the same pattern as writing a PRD before handing work to engineering.",
      },
      {
        id: "9-3",
        title: "Describe it to AI",
        difficulty: "core",
        goal: "Open a new file or project and give AI your mini-spec from the previous exercise.",
        hint: "Paste your spec into the chat and say: \"Build this for me as a single HTML page with inline CSS and JS. Here's the spec: [your spec].\"",
        outcome: "AI generates a first pass of your idea that you can see in the browser.",
        proTip: null,
      },
      {
        id: "9-4",
        title: "Iterate to a working prototype",
        difficulty: "stretch",
        goal: "Go back and forth with AI, refining until you have something you could show a colleague.",
        hint: "Keep giving feedback -- \"make the table wider\", \"add a column for priority\", \"the colors don't look right, use a blue theme\".",
        outcome: "You have a prototype that demonstrates your idea visually.",
        proTip: "Screenshot your prototype and share it in Slack -- it communicates ideas faster than a written spec.",
      },
    ],
  },
  {
    id: 10,
    title: "Ship It",
    theme: "Learn the basics of version control",
    exercises: [
      {
        id: "10-1",
        title: "Check your changes",
        difficulty: "warm-up",
        goal: "Ask AI to explain what git status and git diff show you.",
        hint: "Run git status and git diff and explain what each section means.",
        outcome: "You understand which files you've changed and what the changes look like.",
        proTip: null,
      },
      {
        id: "10-2",
        title: "Create a branch",
        difficulty: "core",
        goal: "Ask AI to create a new branch for your changes.",
        hint: "Create a new git branch called 'my-dashboard-changes' and explain why branches are useful.",
        outcome: "You're on a new branch with your changes, and you understand that branches let you experiment without affecting the original code.",
        proTip: null,
      },
      {
        id: "10-3",
        title: "Write a commit message",
        difficulty: "core",
        goal: "Ask AI to help you stage and commit your work with a clear message.",
        hint: "Help me commit my changes with a clear commit message that describes what I changed and why.",
        outcome: "Your changes are committed with a descriptive message.",
        proTip: null,
      },
      {
        id: "10-4",
        title: "Understand PRs",
        difficulty: "stretch",
        goal: "Ask AI to explain what a pull request is and when a PM might use one.",
        hint: "Explain what a pull request is, how it works, and give me an example of when a PM would create one vs. just prototyping locally.",
        outcome: "You understand PRs as a way to propose changes for review -- useful when your prototype is ready to become real code.",
        proTip: "Even if you never create a PR, understanding them helps you speak engineering's language in sprint planning.",
      },
      {
        id: "10-5",
        title: "Spot the security risk",
        difficulty: "stretch",
        goal: "Ask AI to review your code for security issues, focusing on hardcoded values and exposed data.",
        hint: "Review my project for security risks. Are there any API keys, passwords, or sensitive data hardcoded in the source files? What should I never commit to git?",
        outcome: "AI explains the concept of environment variables, .gitignore, and why you never put API keys or credentials in source code that gets committed.",
        proTip: "Nearly half of AI-generated code contains security flaws. The most common mistake is hardcoding credentials. When you build real prototypes that connect to APIs, always ask AI: \"Is anything sensitive exposed in this code?\"",
      },
      {
        id: "10-6",
        title: "Write a handoff brief",
        difficulty: "stretch",
        goal: "Ask AI to generate a handoff document that an engineer could use to understand your prototype.",
        hint: "Write a brief for an engineer explaining: what this prototype demonstrates, what decisions were made, what's a hack vs. what should be kept, and what needs real engineering to be production-ready.",
        outcome: "AI generates a structured handoff document that separates \"proof of concept\" from \"production-ready\" code.",
        proTip: "A working prototype with a clear handoff brief changes the PM-eng dynamic. Instead of writing a Jira ticket describing what you want, you're showing a working version and explaining what needs to be hardened. Engineers can evaluate the approach rather than interpret your requirements from scratch.",
      },
    ],
  },
];

export const TOTAL_EXERCISES = levels.reduce(
  (sum, level) => sum + level.exercises.length,
  0
);
