export type Difficulty = "warm-up" | "core" | "stretch";

export interface Exercise {
  readonly id: string;
  readonly title: string;
  readonly difficulty: Difficulty;
  readonly goal: string;
  readonly hint: string;
  readonly outcome: string;
  readonly proTip: string | null;
}

export interface SetupStep {
  readonly id: string;
  readonly title: string;
  readonly instructions: string;
  readonly verify: string;
  readonly proTip: string | null;
}

export interface SetupLevel {
  readonly id: number;
  readonly title: string;
  readonly theme: string;
  readonly type: "setup";
  readonly exercises: readonly SetupStep[];
}

export interface ExerciseLevel {
  readonly id: number;
  readonly title: string;
  readonly theme: string;
  readonly type: "exercise";
  readonly exercises: readonly Exercise[];
}

export type Level = SetupLevel | ExerciseLevel;

export const levels: readonly Level[] = [
  {
    id: 0,
    title: "Get Set Up",
    theme: "Install your tools and open your first project",
    type: "setup",
    exercises: [
      {
        id: "0-1",
        title: "Install Cursor",
        instructions: "Go to cursor.com, download for your operating system, install it, and open it. When prompted, you can sign in or skip for now.",
        verify: "Cursor opens and you see a welcome screen or an empty editor.",
        proTip: "Cursor is built on VS Code. It has a built-in AI chat and terminal -- if you get stuck on any of the next steps, open the chat (Cmd+L) and ask for help. If Cursor asks you to choose a plan, the free tier works fine for this workshop.",
      },
      {
        id: "0-2",
        title: "Install Homebrew",
        instructions: "Open Cursor's built-in terminal (Ctrl+` or View > Terminal) and copy-paste this command -- do not type it by hand:\n/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"",
        verify: "Run brew --version -- you should see a version number.",
        proTip: "This may ask for your Mac password -- that's normal. The install takes a few minutes. Windows? Skip Homebrew -- you don't need it. You'll install Git and Node with separate downloads in the next steps.",
      },
      {
        id: "0-3",
        title: "Install Git",
        instructions: "In Cursor's terminal, run brew install git.",
        verify: "git --version prints something like \"git version 2.x.x\".",
        proTip: "Windows? Download Git from git-scm.com and accept the defaults.",
      },
      {
        id: "0-4",
        title: "Install Node.js",
        instructions: "In Cursor's terminal, run brew install node.",
        verify: "node --version prints something like \"v20.x.x\" or higher.",
        proTip: "Windows? Download Node.js from nodejs.org (pick the LTS version). Run the installer, then run node --version in the terminal to verify.",
      },
      {
        id: "0-5",
        title: "Create a GitHub account",
        instructions: "Go to github.com and sign up (or sign in if you already have an account). Verify your email address.",
        verify: "You can visit github.com and see your profile page.",
        proTip: null,
      },
      {
        id: "0-6",
        title: "Clone this project",
        instructions: "In Cursor's terminal, run:\ngit clone [repo-url] vibe-coding-starter\ncd vibe-coding-starter\nReplace [repo-url] with the URL your facilitator shared.",
        verify: "Running ls shows files like index.html, main.ts, and style.css.",
        proTip: "\"clone\" means \"download a copy.\" Your computer now has a full copy you can change without affecting anyone else. Windows? Use dir instead of ls if needed.",
      },
      {
        id: "0-7",
        title: "Open the project in Cursor",
        instructions: "In Cursor, go to File > Open Folder and select the vibe-coding-starter folder you cloned.",
        verify: "The left sidebar shows index.html, main.ts, style.css, data/, and other project files.",
        proTip: "Opening a folder (not a single file) is key -- it gives the AI context about the entire project, not just one file.",
      },
      {
        id: "0-8",
        title: "Start the dev server",
        instructions: "In Cursor's terminal, run:\nnpm install\nnpm start\nClick the URL that appears (usually http://localhost:5173).",
        verify: "Your browser shows a \"Site Dashboard\" page with summary cards and a table of mock customer sites.",
        proTip: "The dev server watches for changes -- when you edit a file and save, the browser updates automatically. This is the magic of vibe coding: change, save, see.",
      },
    ],
  },
  {
    id: 1,
    title: "Explore and Orient",
    theme: "Learn to ask your AI tool questions about code",
    type: "exercise",
    exercises: [
      {
        id: "1-1",
        title: "What does this project do?",
        difficulty: "warm-up",
        goal: "Ask your AI tool to explain the project structure and what each file does.",
        hint: "Can you explain what this project does and walk me through each file?",
        outcome: "You understand the core files: index.html is the page, main.ts has the dashboard logic, style.css has the styling, and data/sites.json has the mock data. You may also notice exercises.ts and exercise-data.ts which power the exercise panel.",
        proTip: null,
      },
      {
        id: "1-2",
        title: "Explain a function",
        difficulty: "core",
        goal: "Ask AI to explain how the table gets built, in plain English.",
        hint: "Explain how the sites table gets populated with data, step by step, in non-technical language.",
        outcome: "AI breaks down that it takes filtered site data, creates a table row for each site, fills in columns like name, owner, product, status, CSAT, revenue, and created date, then replaces the table contents.",
        proTip: null,
      },
      {
        id: "1-3",
        title: "Where does the data come from?",
        difficulty: "core",
        goal: "Ask AI to trace where the site data originates and how it flows to the table.",
        hint: "Trace the data flow -- where does the site data come from and how does it end up in the table?",
        outcome: "You understand the path: sites.json is imported in main.ts, filtered by applyFilters(), then rendered as table rows by renderTable().",
        proTip: null,
      },
      {
        id: "1-4",
        title: "What would happen if...?",
        difficulty: "stretch",
        goal: "Ask AI what would happen if the page didn't run the filters when it first loads.",
        hint: "What would happen if the filters never ran when the page first loaded?",
        outcome: "AI explains the page would load with an empty table and empty summary cards because nothing triggers the initial render. The search and filter controls would still work if you interacted with them -- but you'd see nothing until you did.",
        proTip: null,
      },
      {
        id: "1-5",
        title: "What events fire?",
        difficulty: "stretch",
        goal: "Ask AI what happens under the hood when you change the product filter dropdown.",
        hint: "What happens under the hood when I change the product filter dropdown? Walk me through the chain of events.",
        outcome: "You understand that the 'change' event on #filter-product triggers the applyFilters function, which re-renders everything.",
        proTip: "In real production repos, you can ask AI to find event tracking instrumentation the same way -- \"What analytics event fires when a user clicks [button]?\"",
      },
      {
        id: "1-6",
        title: "Vague vs. structured prompt",
        difficulty: "stretch",
        goal: "See how prompt quality changes AI output by trying two versions of the same question.",
        hint: "First ask: \"Tell me about the data.\" Then ask: \"Give me a summary table showing: count of sites per product type, average CSAT per product type, and total monthly revenue per product type. Format as a markdown table.\" Compare the two responses.",
        outcome: "The vague prompt gives a generic overview. The structured prompt gives you an actionable table you could paste into a Slack message or a slide.",
        proTip: "The pattern is: specify the data source, the exact metrics you want, the grouping, and the output format. This works the same way when you ask AI to analyze a CSV, a database query result, or a QuickSight dataset.",
      },
    ],
  },
  {
    id: 2,
    title: "First Changes",
    theme: "Make your first visible modifications",
    type: "exercise",
    exercises: [
      {
        id: "2-1",
        title: "Change the header text",
        difficulty: "warm-up",
        goal: "Update the header text from \"Site Dashboard\" to something of your own.",
        hint: "Change the dashboard title from 'Site Dashboard' to 'My Product Dashboard'.",
        outcome: "The large header text in your browser shows your new title. You can also update the <title> tag in the <head> to change what shows in the browser tab.",
        proTip: null,
      },
      {
        id: "2-2",
        title: "Change the header color",
        difficulty: "warm-up",
        goal: "Swap the dark header background to a color you like.",
        hint: "The header background is too dark -- make it dark blue instead.",
        outcome: "The header bar in your browser is now the color you chose.",
        proTip: "If you pick a light color, the white text may become invisible. Ask AI to also update the text color if needed.",
      },
      {
        id: "2-3",
        title: "Edit a site name",
        difficulty: "core",
        goal: "Change \"Bella's Bakery\" to a business name you make up.",
        hint: "Change the site called \"Bella's Bakery\" to a business name you make up.",
        outcome: "The first row in the table shows your new business name. If the table disappears after saving, you may have accidentally broken the JSON formatting -- ask AI to check if your sites.json is valid.",
        proTip: null,
      },
      {
        id: "2-4",
        title: "Add yourself",
        difficulty: "stretch",
        goal: "Add a site to sites.json with your own made-up business.",
        hint: "Add a new site to the list with the following info:",
        outcome: "The table now shows 16 rows and the Total Sites card says 16. If the table disappears, ask AI: \"Is my sites.json valid JSON?\"",
        proTip: null,
      },
    ],
  },
  {
    id: 3,
    title: "Read and Understand Data",
    theme: "Use AI to answer PM-relevant questions from the data",
    type: "exercise",
    exercises: [
      {
        id: "3-1",
        title: "Which product has the most sites?",
        difficulty: "warm-up",
        goal: "Ask AI which product type has the most sites.",
        hint: "Which product type has the most sites?",
        outcome: "AI tells you Website Builder and AI Builder each have 4 sites, Managed Hosting for WordPress has 4, and cPanel has 3.",
        proTip: null,
      },
      {
        id: "3-2",
        title: "Who has the worst CSAT?",
        difficulty: "core",
        goal: "Ask AI which site has the lowest CSAT and why that might matter from a PM perspective.",
        hint: "Which site has the lowest CSAT score? What might that tell a product manager?",
        outcome: "AI identifies Paws & Play Pet Care (3.2) and may note it's also inactive -- low satisfaction may have led to churn. Green Valley Farm (3.8) is also inactive with low CSAT, reinforcing the pattern.",
        proTip: null,
      },
      {
        id: "3-3",
        title: "Revenue breakdown",
        difficulty: "core",
        goal: "Ask AI to calculate total monthly revenue grouped by product type.",
        hint: "What's the total monthly revenue for each product type?",
        outcome: "AI gives you revenue totals: Managed Hosting for WordPress ~$199.96, AI Builder ~$142.96, Website Builder ~$64.97, cPanel ~$12.99. Notice that Managed Hosting for WordPress generates the most revenue despite having the same number of sites as others.",
        proTip: null,
      },
      {
        id: "3-4",
        title: "Find the AI Builder users",
        difficulty: "stretch",
        goal: "Ask AI which sites use the AI Builder plugin and what patterns you see.",
        hint: "Which sites use the AI Builder plugin? What patterns do you see?",
        outcome: "AI identifies 8 sites with AI Builder (more than half the portfolio). They tend to have higher CSAT (~6.2 avg vs ~4.4 for non-users) and higher revenue (~$43 avg vs ~$11). Note that non-users include inactive sites, which skews the comparison.",
        proTip: "This is the kind of question PMs can ask AI about real product data -- finding patterns without writing SQL.",
      },
    ],
  },
  {
    id: 4,
    title: "Add Features",
    theme: "Extend the dashboard with new functionality",
    type: "exercise",
    exercises: [
      {
        id: "4-1",
        title: "Add a Page Views column",
        difficulty: "warm-up",
        goal: "The data has pageViews but it's not displayed -- add it to the table.",
        hint: "The data has pageViews but it's not displayed -- add it to the table.",
        outcome: "A new Page Views column appears in the table with formatted numbers.",
        proTip: null,
      },
      {
        id: "4-2",
        title: "Add a Region column",
        difficulty: "core",
        goal: "Sites have a region but it's not shown anywhere -- add it to the table.",
        hint: "Each site has a region but it's not visible -- add it to the table.",
        outcome: "A Region column appears showing US-West, US-East, US-Central, EU.",
        proTip: null,
      },
      {
        id: "4-3",
        title: "Conditional row highlighting",
        difficulty: "core",
        goal: "Make rows with CSAT below 4.0 stand out visually.",
        hint: "Make rows with CSAT below 4.0 stand out so I can spot problem sites at a glance.",
        outcome: "Paws & Play (3.2) and Green Valley Farm (3.8) rows are highlighted.",
        proTip: "One site (The Vinyl Lounge) has no CSAT score at all -- make sure your highlighting skips sites with missing data.",
      },
      {
        id: "4-4",
        title: "New summary card",
        difficulty: "stretch",
        goal: "Add a \"Total Page Views\" card to the summary section at the top.",
        hint: "I want to see total page views at a glance, like the other summary cards at the top.",
        outcome: "A fifth card appears in the summary row showing total page views.",
        proTip: "Notice how the card updates when you filter -- the same filtering logic applies automatically.",
      },
    ],
  },
  {
    id: 5,
    title: "Bug Hunt",
    theme: "Find and fix a real bug hidden in the code",
    type: "exercise",
    exercises: [
      {
        id: "5-1",
        title: "Spot the discrepancy",
        difficulty: "warm-up",
        goal: "Manually add up the monthly revenue for all 15 sites. Does the dashboard total match?",
        hint: "Add up all the monthly revenue values from the site data. Does it match what the dashboard shows?",
        outcome: "The dashboard shows a lower number than your manual calculation -- something is wrong.",
        proTip: null,
      },
      {
        id: "5-2",
        title: "Ask AI to find the bug",
        difficulty: "core",
        goal: "Tell AI the revenue total seems wrong and see if it can locate the issue.",
        hint: "The Monthly Revenue total on the dashboard doesn't match what I calculated manually. Can you find the bug?",
        outcome: "AI identifies the off-by-one error in the for loop in calculateStats (i < filteredSites.length - 1 should be i < filteredSites.length).",
        proTip: null,
      },
      {
        id: "5-3",
        title: "Fix it",
        difficulty: "core",
        goal: "Use AI to fix the bug and verify the total is now correct.",
        hint: "Fix the revenue calculation bug you found and verify the total is now correct.",
        outcome: "The Monthly Revenue card now shows the correct total including the last site's revenue.",
        proTip: null,
      },
      {
        id: "5-4",
        title: "Understand git blame",
        difficulty: "stretch",
        goal: "Ask AI to show you which commit introduced the bug.",
        hint: "Use git log or git blame to show me which commit introduced the bug in the revenue calculation.",
        outcome: "AI shows you the commit \"Add dashboard logic with filtering and summary stats\" introduced the off-by-one error.",
        proTip: "In real projects, git blame helps PMs understand when and why a change was made -- useful for incident timelines.",
      },
    ],
  },
  {
    id: 6,
    title: "Data Analysis",
    theme: "Turn raw data into actionable insights",
    type: "exercise",
    exercises: [
      {
        id: "6-1",
        title: "Sort the table",
        difficulty: "core",
        goal: "Make table column headers clickable to sort ascending/descending.",
        hint: "Make the table sortable -- I should be able to click any column header to sort by it, and click again to reverse.",
        outcome: "Clicking \"CSAT\" sorts sites by CSAT score, clicking again reverses the order.",
        proTip: null,
      },
      {
        id: "6-2",
        title: "Revenue by product",
        difficulty: "core",
        goal: "Add a visible breakdown showing total revenue grouped by product type.",
        hint: "I want to see revenue broken down by product type somewhere on the dashboard.",
        outcome: "A new section appears showing revenue totals per product type.",
        proTip: null,
      },
      {
        id: "6-3",
        title: "CSAT distribution",
        difficulty: "core",
        goal: "Show how many sites fall into each CSAT bucket (good/ok/bad).",
        hint: "Show me a breakdown of how many sites have good CSAT (5.5+), ok (4.0-5.4), and bad (below 4.0). Skip sites with no score.",
        outcome: "A breakdown showing the count per bucket (e.g., 8 good, 4 ok, 2 bad). Note: one site has no CSAT rating and should be excluded.",
        proTip: null,
      },
      {
        id: "6-4",
        title: "Top performers",
        difficulty: "stretch",
        goal: "Highlight or badge the top 3 sites by page views.",
        hint: "I want the top 3 sites by page views to stand out in the table -- badge them or highlight them somehow.",
        outcome: "The 3 highest-traffic sites have a visible badge or highlight.",
        proTip: null,
      },
    ],
  },
  {
    id: 7,
    title: "Visualization",
    theme: "Add charts and visual data stories",
    type: "exercise",
    exercises: [
      {
        id: "7-1",
        title: "Bar chart",
        difficulty: "core",
        goal: "Add a bar chart showing CSAT scores by site using pure HTML/CSS.",
        hint: "Add a bar chart showing CSAT scores for each site. Keep it simple -- no charting library, just use CSS.",
        outcome: "A bar chart appears with each site's CSAT score visualized as colored bars, generated from the live data.",
        proTip: null,
      },
      {
        id: "7-2",
        title: "Pie chart",
        difficulty: "core",
        goal: "Add a pie chart showing the product type distribution using CSS.",
        hint: "Add a pie chart showing the product type distribution with a legend. No charting library -- just CSS.",
        outcome: "A pie chart appears with 4 segments showing the product mix, with a legend identifying each color.",
        proTip: null,
      },
      {
        id: "7-3",
        title: "Make it interactive",
        difficulty: "stretch",
        goal: "Add hover tooltips or click interactions to a chart. You need to complete the bar chart exercise (7-1) first.",
        hint: "Make the bar chart interactive -- I should see the exact score and site name when I hover over a bar.",
        outcome: "Hovering over chart bars reveals the site name and exact CSAT score.",
        proTip: "For production dashboards you'd use Chart.js or D3 -- but pure CSS charts are great for quick prototypes and keep this project dependency-free.",
      },
      {
        id: "7-4",
        title: "Build a data presentation",
        difficulty: "stretch",
        goal: "Create a presentation-ready summary page that tells a story with your charts and data analysis.",
        hint: "Create a new HTML page called presentation.html that tells a data story about our site portfolio. Include: an executive summary with key metrics, the charts from the previous exercises (or new ones), a \"risks and opportunities\" section highlighting low-CSAT sites and high-revenue products, and a recommendation slide. Style it like a slide deck -- one section per screen, large fonts, minimal text.",
        outcome: "A standalone page that reads like a presentation -- someone could scroll through it and understand the portfolio health, key risks, and your recommendations without opening the dashboard.",
        proTip: "PMs spend hours building slide decks from data. Vibe coding lets you generate a data-driven presentation directly from the source -- and it updates automatically when the data changes. Try sharing the URL instead of exporting slides.",
      },
    ],
  },
  {
    id: 8,
    title: "Build a New View",
    theme: "Create something that doesn't exist yet",
    type: "exercise",
    exercises: [
      {
        id: "8-1",
        title: "Site detail panel",
        difficulty: "stretch",
        goal: "When you click a site name in the table, show a detail panel with all of that site's information.",
        hint: "When I click a site name, show me all the details for that site -- plan, plugins, page views, region. Show it inline, not as a sidebar (the exercise panel is already there). Let me close it too.",
        outcome: "Clicking a site name opens a detail view showing fields not in the table. Clicking the close button (or clicking a different site) dismisses it.",
        proTip: null,
      },
      {
        id: "8-2",
        title: "Comparison mode",
        difficulty: "stretch",
        goal: "Let users select two sites and see a side-by-side comparison.",
        hint: "Let me select two sites and compare them side by side -- all their fields including plan, plugins, page views, and region.",
        outcome: "Selecting two sites and clicking Compare shows their stats side-by-side.",
        proTip: null,
      },
      {
        id: "8-3",
        title: "Executive summary view",
        difficulty: "stretch",
        goal: "Add a toggleable executive summary view within the existing page.",
        hint: "Add a way to toggle between the detailed table and a high-level executive summary showing totals, averages, and top/bottom performers.",
        outcome: "A toggle switches between the detailed table and a high-level executive view, all within the same page.",
        proTip: null,
      },
      {
        id: "8-4",
        title: "Build from a screenshot",
        difficulty: "stretch",
        goal: "Take a screenshot of any UI you like (a competitor's dashboard, a Figma mock, a sketch on paper) and use it as an AI input to generate code.",
        hint: "Cursor supports image paste in the chat window (Cmd+L) -- try dragging a screenshot into it. If that doesn't work, open claude.ai or chatgpt.com in your browser (free accounts work). Say: \"Build me a component that looks like this screenshot. Use the same layout and visual style but populate it with data from sites.json.\" If you used an external tool, paste the generated code back into Cursor and ask it to integrate it into your project.",
        outcome: "AI generates a new section or component that visually matches your reference image, wired to real data.",
        proTip: "This is one of the highest-leverage PM workflows -- go from a whiteboard sketch or Figma mock to a working prototype in minutes. Some PMs use this to estimate LOE by asking \"how complex would this be to build?\" after the AI generates the code.",
      },
    ],
  },
  {
    id: 9,
    title: "Prototype Your Own Idea",
    theme: "Apply vibe coding to your actual PM work",
    type: "exercise",
    exercises: [
      {
        id: "9-1",
        title: "Identify a real problem",
        difficulty: "warm-up",
        goal: "Think about a task from your PM workflow that you currently do manually or ask engineering for help with.",
        hint: "Reflection (no AI prompt needed): Think of something you do manually or ask engineering to help with. Examples: a prioritization scorecard, a competitive comparison table, a release checklist, a customer feedback tracker.",
        outcome: "You have a concrete idea for something you want to build. You can describe it in one sentence.",
        proTip: null,
      },
      {
        id: "9-2",
        title: "Write a mini-spec first",
        difficulty: "core",
        goal: "Before prompting AI, write a short spec for your idea -- 3-5 bullet points covering what it does, what data it needs, and what the output looks like.",
        hint: "Write something like: \"Tool: Priority Scorecard. Purpose: Rank feature requests by impact and effort. Data: a list of features with name, impact score (1-5), effort score (1-5), and requestor. Output: a table sorted by impact/effort ratio with color-coded priority bands.\"",
        outcome: "You have a structured spec you can hand to AI instead of a vague description.",
        proTip: "PMs who write a spec before prompting get dramatically better first-pass output. It also becomes the acceptance criteria -- you can tell AI \"this doesn't match the spec, the table should be sorted by ratio\" instead of vague feedback. This is the same pattern as writing a PRD before handing work to engineering.",
      },
      {
        id: "9-3",
        title: "Describe it to AI",
        difficulty: "core",
        goal: "Create a new file (e.g., my-tool.html in this project folder) and give AI your mini-spec from the previous exercise.",
        hint: "Paste your spec into the chat and say: \"Build this for me as a single HTML page with inline CSS and JS. Here's the spec: [your spec].\"",
        outcome: "AI generates a first pass of your idea that you can see in the browser.",
        proTip: null,
      },
      {
        id: "9-4",
        title: "Iterate to a working prototype",
        difficulty: "stretch",
        goal: "Go back and forth with AI, refining until you have something you could show a colleague.",
        hint: "Keep giving feedback -- \"make the table wider\", \"add a column for priority\", \"the colors don't look right, use a blue theme\".",
        outcome: "You have a prototype that demonstrates your idea visually.",
        proTip: "Screenshot your prototype and share it in Slack -- it communicates ideas faster than a written spec.",
      },
    ],
  },
  {
    id: 10,
    title: "Ship It",
    theme: "Learn the basics of version control",
    type: "exercise",
    exercises: [
      {
        id: "10-1",
        title: "Check your changes",
        difficulty: "warm-up",
        goal: "Ask AI to explain what git status and git diff show you. (Make sure you've completed a few exercises from earlier levels first so you have some changed files.)",
        hint: "Run git status and git diff and explain what each section means.",
        outcome: "You understand which files you've changed and what the changes look like.",
        proTip: null,
      },
      {
        id: "10-2",
        title: "Create a branch",
        difficulty: "core",
        goal: "Ask AI to create a new branch for your changes.",
        hint: "Create a new git branch called 'my-dashboard-changes', switch to it, and explain why branches are useful.",
        outcome: "You're on a new branch with your changes, and you understand that branches let you experiment without affecting the original code.",
        proTip: "Think of a branch as a parallel copy of your project. You can experiment freely on a branch, and the original code stays untouched on the main branch.",
      },
      {
        id: "10-3",
        title: "Write a commit message",
        difficulty: "core",
        goal: "Ask AI to help you stage and commit your work with a clear message.",
        hint: "Show me how to stage my changed files with git add and then commit them with a clear message that describes what I changed and why.",
        outcome: "AI walks you through staging files (git add) and committing (git commit). Your changes are committed with a descriptive message.",
        proTip: "Staging is like packing a box before shipping it. You pick which changes go into this commit with git add, then seal it with git commit.",
      },
      {
        id: "10-4",
        title: "Understand PRs",
        difficulty: "stretch",
        goal: "Ask AI to explain what a pull request is and when a PM might use one.",
        hint: "Explain what a pull request is, how it works, and give me an example of when a PM would create one vs. just prototyping locally.",
        outcome: "You understand PRs as a way to propose changes for review -- useful when your prototype is ready to become real code.",
        proTip: "Even if you never create a PR, understanding them helps you speak engineering's language in sprint planning.",
      },
      {
        id: "10-5",
        title: "Spot the security risk",
        difficulty: "stretch",
        goal: "Ask AI to review your code for security issues, focusing on hardcoded values and exposed data.",
        hint: "Review my project for security risks. Are there any API keys, passwords, or sensitive data hardcoded in the source files? What should I never commit to git?",
        outcome: "AI finds the hardcoded demo API key in main.ts and explains why it should be moved to an environment variable. It may also flag that .env is not in .gitignore -- meaning if you created a .env file, it could accidentally get committed.",
        proTip: "Nearly half of AI-generated code contains security flaws. The most common mistake is hardcoding credentials. When you build real prototypes that connect to APIs, always ask AI: \"Is anything sensitive exposed in this code?\"",
      },
      {
        id: "10-6",
        title: "Write a handoff brief",
        difficulty: "stretch",
        goal: "Ask AI to generate a handoff document that an engineer could use to understand your prototype.",
        hint: "Write a brief for an engineer explaining: what this prototype demonstrates, what decisions were made, what's a hack vs. what should be kept, and what needs real engineering to be production-ready.",
        outcome: "AI generates a structured handoff document that separates \"proof of concept\" from \"production-ready\" code.",
        proTip: "A working prototype with a clear handoff brief changes the PM-eng dynamic. Instead of writing a Jira ticket describing what you want, you're showing a working version and explaining what needs to be hardened. Engineers can evaluate the approach rather than interpret your requirements from scratch.",
      },
    ],
  },
  {
    id: 11,
    title: "AI-Powered PM Workflows",
    theme: "Use AI to research, plan, and create tickets",
    type: "exercise",
    exercises: [
      {
        id: "11-1",
        title: "Research a product question",
        difficulty: "warm-up",
        goal: "Ask AI to research a product topic and synthesize findings you can act on.",
        hint: "Research the top 5 features users expect from an AI website builder in 2026. For each feature, include: what it does, why users want it, and which competitors already offer it. Format as a markdown table.",
        outcome: "AI returns a structured research summary with competitive context you could paste into a strategy doc or share with your team. The table format makes it easy to compare features across competitors.",
        proTip: "The key to good AI research is specificity. \"Research AI builders\" gives you a Wikipedia summary. \"Top 5 features users expect, with competitor coverage\" gives you something you can bring to a planning meeting.",
      },
      {
        id: "11-2",
        title: "Deep-dive a competitor",
        difficulty: "core",
        goal: "Ask AI to do a detailed competitive analysis on a specific product or company.",
        hint: "Do a competitive analysis of [competitor name]'s AI website builder. Cover: target audience, pricing model, key differentiators, weaknesses, and what we could learn from them. Include specific examples, not just generic bullet points.",
        outcome: "AI produces a structured competitive brief with enough detail to inform a product strategy discussion. You can identify gaps in your own product and opportunities to differentiate.",
        proTip: "Follow up with \"Now compare this to our product's strengths and weaknesses\" to get AI to synthesize the research into actionable insights. Layer your prompts -- research first, then analyze.",
      },
      {
        id: "11-3",
        title: "Synthesize research into themes",
        difficulty: "core",
        goal: "Take research from the previous exercises and ask AI to identify the top themes and opportunities.",
        hint: "Based on the competitive research and feature analysis we just did, identify the top 3 strategic themes. For each theme: name it, explain why it matters, list supporting evidence from the research, and suggest one concrete product bet we could make.",
        outcome: "AI distills broad research into focused strategic themes with supporting evidence. Each theme has a clear \"so what\" -- a product bet you could pitch to leadership.",
        proTip: null,
      },
      {
        id: "11-4",
        title: "Build a prioritized roadmap",
        difficulty: "core",
        goal: "Ask AI to turn your research themes into a prioritized roadmap with sequencing rationale.",
        hint: "Turn these 3 strategic themes into a quarterly roadmap for the next 2 quarters. For each item include: title, description, target quarter, priority (P0/P1/P2), estimated effort (S/M/L), expected impact, and dependencies. Prioritize based on user impact and competitive urgency. Explain your sequencing rationale.",
        outcome: "AI generates a roadmap table with clear prioritization logic. Items are sequenced based on dependencies and impact, not just listed randomly. The sequencing rationale helps you defend the plan in stakeholder reviews.",
        proTip: "AI is great at generating a first-draft roadmap, but the real value is in the conversation. Push back: \"Why is this P1 and not P0?\" or \"What if we only had one quarter?\" The AI will adapt its reasoning and help you stress-test the plan.",
      },
      {
        id: "11-5",
        title: "Create Jira tickets from the roadmap",
        difficulty: "stretch",
        goal: "Ask AI to break a roadmap item into implementation-ready Jira tickets with acceptance criteria.",
        hint: "Take the top P0 item from our roadmap and break it into Jira tickets. For each ticket include: title, type (Epic/Story/Task), description, acceptance criteria (as testable statements), story points estimate, and dependencies on other tickets. Create one Epic and 3-5 Stories underneath it.",
        outcome: "AI generates a set of structured tickets with an Epic as the parent and Stories as children. Each Story has clear acceptance criteria that an engineer could pick up without a follow-up conversation. Dependencies between tickets are explicit.",
        proTip: "The best Jira tickets answer three questions: What are we building? How do we know it's done? What does this depend on? If AI generates vague acceptance criteria like \"works correctly,\" push back: \"Make the acceptance criteria specific and testable -- an engineer should be able to verify each one without asking me.\"",
      },
    ],
  },
];

export const TOTAL_EXERCISES = levels.reduce(
  (sum, level) => sum + level.exercises.length,
  0
);
